name: GitHub Actions Demo 2
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: pull_request

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    permissions:
      id-token: write          # <-- this populates the two env vars
    steps:
      - uses: actions/checkout@v6
      - run: |
          echo "$ACTIONS_ID_TOKEN_REQUEST_TOKEN"
          echo "$ACTIONS_ID_TOKEN_REQUEST_URL"
